### ISSUE TITLE
catalina.properties

### ISSUE THREAD

**Issue by rbkpro** [mikelasla/alfresco#2]
Why we don't just skip all jar :
tomcat.util.scan.DefaultJarScanner.jarsToSkip=*.jar

**Comment by mikelasla** [comment]
Hi 
Sorry for the late respond, kind of busy. Can you give me some more context about what you need  the project to do?

**Comment by rbkpro** [comment]
I want to boost the start-up of tomcat instance by skipping the TLD scan which explained in this article https://wiki.apache.org/tomcat/HowTo/FasterStartUp 
But supprisingly I found in catalina.properties that you didn't skip all jars 
https://github.com/mikelasla/alfresco/blob/master/assets/tomcat/catalina.properties 

Please, could you explain that for me? 

Thanks

**Comment by mikelasla** [comment]
That's the default value for `tomcat.util.scan.DefaultJarScanner.jarsToSkip` on Tomcat 7.0.69
I need to override catalina.properties file just to set the shared.loader property needed by Alfresco to configure the application from outside the war, nothing else.

**Comment by rbkpro** [comment]
@mikelasla Thanks
