### ISSUE TITLE
Oracle JDK 1.8.0.121 is hidden behind login page

### ISSUE THREAD

**Issue by christian-scheible** [mikelasla/alfresco#3]
It seems that Oracle changed the way it handles its archived JDKs. It's no longer possible to download the JDK 1.8.0.121 without logging in.

http://download.oracle.com/otn/java/jdk/8u121-b13/e9e7ea248e2c4826b92b3f075a80e441/jdk-8u121-linux-x64.rpm

I worked around this by downloading manually, adding it to assets and using docker COPY instead of wget.

But maybe there is a better solution for this problem like using OpenJDK.

**Comment by mikelasla** [comment]
Sure! Thanks for the feedback
I'll change to openJDK as soon as i get some time

**Comment by mikelasla** [comment]
New version published, it has some changes
* Debian based (tomcat:7-jre8 official dockerhub library)
* OpenJDK 1.8
* Solr4 is gone and now comes configured to use solr6 (provided by docker-compose, also docker run instructions provided on readme)
